deployment:
  imageRepo: 485658242739.dkr.ecr.us-east-1.amazonaws.com/roboshop/catalogue:ab8c78041
  imageVersion: IMAGE_VERSION
service:
  servicePort: 8080 #default value .we can override this value from command line.
